# Copyright 2025 Google LLC
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Bundler

on:
  workflow_dispatch:
  schedule:
    - cron: "10 13,16,20 * * 1-5"  # Three times a day, Monday through Friday
    # CST: 07:10, 10:10, 14:10
    # CDT: 08:10, 11:10, 15:10
    # UTC: 13:10, 16:10, 20:10

jobs:
  bundler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - run: pipenv install
      - name: write config file
        run: |
          cat << EOF > ./config.py
          ${{ secrets.CONFIG }}
          EOF
      - run: pipenv run python address_validation.py
      - run: pipenv run python bundler.py
